### ISSUE TITLE
Interaction score chart

### ISSUE THREAD

**Issue by cjosu** [dgidb/dgidb-v5#100]
This is the first chart the user sees when querying interactions, but it's not immediately obvious what it represents. If the chart itself can't be simplified (or broken out into multiple charts), we might consider adding some more helpful labeling. 

<img width="984" alt="image" src="https://user-images.githubusercontent.com/88686663/165795607-96797411-607d-4d7f-a575-9e02f1bc22fe.png">

**Comment by mcannon068nw** [comment]
after consulting with local math expert, the usefulness and feasibility of this graph type seems dubious. Am currently looking into different options to still display metrics involving interaction score that are more readily interpretable and easier to implement
