### ISSUE TITLE
Do something about the volume of NCI records

### ISSUE THREAD

**Issue by jsstevenson** [dgidb/dgidb-v5#113]
The NCI importer pulls somewhere on the order of hundreds of thousands of entries (I let it run for a few hours and it still hadn't finished so I stopped it manually). This is pretty far off from previous DGIdb entries (which were like ~6k interactions). If this is correct behavior, then it's correct, but it's a pretty unwieldy size either way.

**Comment by mcannon068nw** [comment]
Evidence codes are way to go. As written, importer grabs over 100000 records without any evidence support (EvidenceCode = NaN or not_assigned)

34 possible evidence codes with varying support, if we use those with physical experimental evidence (contains EV-EXP) as minimum evidence criteria, we pull in ~90000 records down from original 317907.

If we only use evidence code EV-EXP-IPI (inferred from physical reaction), we pull in 6512 claims, which is closer in line with v4 numbers

**Comment by mcannon068nw** [comment]
Looking into using previous version's dataset for this.

Will revisit this issue
