### ISSUE TITLE
Drug Record design

### ISSUE THREAD

**Issue by cjosu** [dgidb/dgidb-v5#136]

**Comment by jsstevenson** [comment]
If I remember correctly, the plan is to include in this page a list of links out to FDA drug applications. These are stored internally as CURIEs - eg `drugsatfda.anda:012345` or `drugsatfda.nda:987654` - but I think this is a pretty uncommon way of representing them. I would propose instead that the client does some simple string manipulation to do something like

 * NDA: 987654
 * ANDA: 012345

Per eg https://www.accessdata.fda.gov/scripts/cder/daf/index.cfm?event=overview.process&varApplNo=021588
