### ISSUE TITLE
Source Summary page

### ISSUE THREAD

**Issue by cjosu** [dgidb/dgidb-v5#170]
When browsing sources, each should have summary data (either in a separate page or expandable)

**Comment by katiestahl** [comment]
collab with @jsstevenson to address various changes to the way this page is handled #ReduceTheJank

**Comment by katiestahl** [comment]
pulled out of sprint for now - need to discuss with the group how we want this page to behave or potentially change, as there is already an existing implementation for v5

**Comment by katiestahl** [comment]
addressed styling issues and reworked this in #243. If additional changes are requested, they should be added to a new issue
