### ISSUE TITLE
Query gene list from category

### ISSUE THREAD

**Issue by cjosu** [dgidb/dgidb-v5#173]
When browsing categories and clicking into a category, need to return paginated list of associated genes (along with sources that include that gene under the category). 

So given a category + list of sources, return a list of {gene, gene_description, sources}

Example [here](https://www.dgidb.org/druggable_gene_categories/ABC%20TRANSPORTER?sources=BaderLabGenes,CIViC,COSMIC,CarisMolecularIntelligence,FoundationOneGenes,GO,HingoraniCasas,HopkinsGroom,HumanProteinAtlas,IDG,MskImpact,Oncomine,Pharos,RussLampel,Tempus,dGene)

**Comment by jsstevenson** [comment]
Associated w/ #220

**Comment by jsstevenson** [comment]
duplicate
