### ISSUE TITLE
Missing indication field in results

### ISSUE THREAD

**Issue by cjosu** [dgidb/dgidb-v5#194]
In Interactions by Drug, certain records are missing an indication field. Might be a data issue?

**Comment by mcannon068nw** [comment]
Re: meeting, did some investigation to try to understand what this issue might be about: 

After some investigation of graphql fields and what is currently built under Interactions by Drug, I think the issue might be a misunderstanding of how the data is presented. In the interactions results, our design documents intended for sample indications to be displayed within the results table in addition to scores, interaction type, and approval status. My suspicion is that there was uncertainty whether every drug is expected to have an indication or not.

Indications can be returned within an InteractionAttribute field and can be grabbed for display if it exists, but it is not always guaranteed to be present. In these cases we could display "Not Available" or something along those lines.
![Screen Shot 2022-12-05 at 2 11 25 PM](https://user-images.githubusercontent.com/87494086/205724054-a04b10ab-e805-443e-aebf-b224f3aae1c2.png)
