### ISSUE TITLE
Drug charts breaking styling

### ISSUE THREAD

**Issue by cjosu** [dgidb/dgidb-v5#195]
Charts escaping parent div

**Comment by katiestahl** [comment]
<img width="1668" alt="Screen Shot 2022-07-25 at 10 41 01 AM" src="https://user-images.githubusercontent.com/13563629/180804126-e301750e-e2bb-4267-aab4-d93280f60cdf.png">

**Comment by katiestahl** [comment]
Should be fixed from #209
