### ISSUE TITLE
Create page for v5 API documentation

### ISSUE THREAD

**Issue by katiestahl** [dgidb/dgidb-v5#199]
Examples:
https://github.com/graphql/graphql-playground
https://civicdb.org/api/graphiql
https://pharos.nih.gov/api

**Comment by katiestahl** [comment]
** need requirements for functionality and desired appearance/behavior. 
should we just do a swagger page for this?

**Comment by mcannon068nw** [comment]
@acoffman and I tried playing around with an implementation of graphql-playground at the hackathon. Trial imiplementation is on graphqlPlayground branch. Getting a weird 'Rules of Hooks' bug.

**Comment by jsstevenson** [comment]
Remaining to-do's:

- [ ] plug into backend
- [ ] write example queries
- [ ] frontend styling

**Comment by jsstevenson** [comment]
completed in #302
