### ISSUE TITLE
Entrez/Ensembl gene claims discrepancy 

### ISSUE THREAD

**Issue by jsstevenson** [dgidb/dgidb-v5#224]
The v5 gene grouper provides considerably fewer gene claims from ensembl and ncbi/entrez-gene (on the order of an ~80% dropoff). We should check this out.

**Comment by mcannon068nw** [comment]
@jsstevenson per meeting, I think we should be good to go ahead and close this issue as solved?

**Comment by jsstevenson** [comment]
Agreed
