### ISSUE TITLE
Drug Approval

### ISSUE THREAD

**Issue by mcannon068nw** [dgidb/dgidb-v5#24]
Evaluate DGIdb current filtering strategy/language against planned approval enum expansion for all sources:

```
CHEMBL_1
CHEMBL_2
CHEMBL_3
CHEMBL_4
CHEMBL_WITHDRAWN
FDA_DISCONTINUED
FDA_PRESCRIPTION
FDA_OTC
FDA_TENTATIVE
GTOPDB_APPROVED
GTOPDB_WITHDRAWN
HEMONC_APPROVED
RXNORM_PRESCRIBABLE
```

**Comment by jsstevenson** [comment]
A few to-do's:

- [ ] Create drug claim approval table, model, graphql type
- [ ] Create drug approval table, model, graphql type
- [ ] Extract ratings from grouper sources
- [ ] Refactor ChEMBL, GtP, DrugBank, other importers to pull approval ratings
- [ ] Clean up errant approval ratings (eg ensure indications are labeled as such)
