### ISSUE TITLE
Refine source metadata

### ISSUE THREAD

**Issue by katiestahl** [dgidb/dgidb-v5#240]
- Need a shortened citation eg "AUTHORLASTNAME et al., YEAR" when there are over 3 authors:

<img width="1728" alt="Screen Shot 2023-01-03 at 1 49 34 PM" src="https://user-images.githubusercontent.com/13563629/210422047-b2ec8185-f282-4f74-88f8-7528e63a1170.png">

- Provide PMID, PMC ID, DOI where available
- Break out citation vs URL refs
- Provide current source version
- Double check source types
- do gene/drug sources need ungrouped #s?

**Comment by jsstevenson** [comment]
working: https://docs.google.com/spreadsheets/d/1Ief5hUGwaKkTVjuSkJ3AgI5bGa_DMLeHJpNsAFg9XUk/edit#gid=0
