### ISSUE TITLE
Warning message in useGetCategories

### ISSUE THREAD

**Issue by acoffman** [dgidb/dgidb-v5#273]
<img width="1031" alt="Screenshot 2023-02-01 at 3 55 40 PM" src="https://user-images.githubusercontent.com/13370/216172490-0647fdbf-3f22-4d60-83b7-ce4225a8ad2f.png">

Not 100% sure what the intent is here, but probably not that. I would guess you probably want `names.length !== 0`.

**Comment by jsstevenson** [comment]
Not sure when, but we apparently fixed this at some point
