### ISSUE TITLE
No versioning of sources on browse sources page

### ISSUE THREAD

**Issue by kcotto** [dgidb/dgidb-v5#309]
In v4.0, we have a concept of versioning for sources (see below) ![Screenshot 2023-03-14 at 10 21 04 AM](https://user-images.githubusercontent.com/22246534/225051896-ee7ffb44-d3ea-428b-95c9-ed67fa4ad3a0.png)
However, [here](https://staging.dgidb.org/browse/sources) we don't have the same concept of versioning.

**Comment by mcannon068nw** [comment]
Consider adding versioning to top right of source in v5 as in v4
