### ISSUE TITLE
Overlapping approval terms

### ISSUE THREAD

**Issue by kcotto** [dgidb/dgidb-v5#313]
![Screenshot 2023-03-14 at 10 00 24 AM](https://user-images.githubusercontent.com/22246534/225059391-54ac57f6-c69f-4cd5-9cbe-31bcda0238e6.png)

It appears that there are overlapping approval terms being imported (i.e. prescribable, approved, prescription, etc). We might want think about harmonizing these into one term such as 'approved'

**Comment by jsstevenson** [comment]
👍 we've thought about overhauling this graphic entirely (ie maybe not a pie chart), but combining like terms is definitely on the to-do list. handling in #246
