### ISSUE TITLE
Potentially sort interaction results on interaction score

### ISSUE THREAD

**Issue by kcotto** [dgidb/dgidb-v5#314]
When you search using a gene term, you can select and deselect different interaction scores (see below). I'm not sure how useful this actually is. I wonder if it would be better to allow for sorting in ascending/descending order.
![Screenshot 2023-03-14 at 11 00 29 AM](https://user-images.githubusercontent.com/22246534/225065282-ee74cb77-b397-4fdf-a36e-1b37433c74f0.png)

**Comment by mcannon068nw** [comment]
addressed by MUI table redesign

**Comment by jsstevenson** [comment]
Completed in #317
