### ISSUE TITLE
Interaction results are not separated by genes

### ISSUE THREAD

**Issue by kcotto** [dgidb/dgidb-v5#316]
Interaction results are mixed when in v4.0 they’re split by search result (either by gene or by drug)

v4
![Screenshot 2023-03-14 at 10 03 46 AM](https://user-images.githubusercontent.com/22246534/225067538-f5f703e2-7f72-4fa6-a051-2b7ae97aae52.png)

v5
![Screenshot 2023-03-14 at 10 04 04 AM](https://user-images.githubusercontent.com/22246534/225067620-f3b42e8c-dcc1-4a4c-8add-10847516b22d.png)

**Comment by jsstevenson** [comment]
I _think_ this is intentional -- the idea being that you can use filters to pick what you want -- but worth revisiting

**Comment by mcannon068nw** [comment]
consider global/server-side sort for these

**Comment by katiestahl** [comment]
changed tag to backend- if this is a feature we want, this logic should exist there
