### ISSUE TITLE
don't display tooltips with no text

### ISSUE THREAD

**Issue by katiestahl** [dgidb/dgidb-v5#329]
if the pmids or sources for an interaction are 0, don't display the tooltip

**Comment by whilekofman** [comment]
Hi this project came up on an aggregator that compiles all opensource projects with issues tagged with good first issue.    I have experience working with both rails and react, and think that a drug to gene interaction database is a pretty cool project to contribute in my free time.    I should be able to look into this for you and potentially some other issues in the project.  Is the project open to outside contributers?  Would I need a local copy of the database to simulate this issue on my end? If so how could I go about getting a copy of the dump file?
