### ISSUE TITLE
support pasting lists of genes/drugs into search bar

### ISSUE THREAD

**Issue by katiestahl** [dgidb/dgidb-v5#350]
users should be able to paste comma separated, tab separated, or newline separated lists of genes/drugs in the search bar. The code should separate these by the commas and turn them into tags

**Comment by mcannon068nw** [comment]
consider file upload for csv as alternative for bulk search

**Comment by mcannon068nw** [comment]
special character selection would need to be well defined (i.e some drugs have spaces in them so the file cannot be space sep)

**Comment by mcannon068nw** [comment]
@katiestahl do you have an estimate for how long this issue will take?

**Comment by katiestahl** [comment]
> @katiestahl do you have an estimate for how long this issue will take?

I don't think this will take any longer than a day to finish up supporting pasting into the search bar. But if we want to do something more complicated, like a file upload for a bulk search, that would take longer. (But I think that should be a separate issue from this one)
