### ISSUE TITLE
Broken links on site

### ISSUE THREAD

**Issue by ChrisSteel-bio** [dgidb/dgidb-v5#459]
I would like to download dgidb data from the site, but all of the website links are currently broken. It would be fantastic if someone could fix this.

**Comment by mcannon068nw** [comment]
Hello @ChrisSteel-bio! Thank you for submitting this issue. 

We are currently working on diagnosing this. We hope to have a fix soon. In the meantime, the TSVs available from the download page are also available from: https://old.dgidb.org/downloads

**Comment by ChrisSteel-bio** [comment]
Hi @mcannon068nw thanks for your quick reply. I checked, and the tsvs from https://old.dgidb.org/downloads aren't up to date. I.e. certain genes give me hits in the new database, yet are completely absent from the tsv download from the old site. "RPS3A" as an example.

**Comment by mcannon068nw** [comment]
A fix for this is in progress. In the meantime, we will host TSVs containing data from the most recent release here:

[dec-2023-categories.csv](https://github.com/dgidb/dgidb-v5/files/13651004/dec-2023-categories.csv)
[dec-2023-drugs.csv](https://github.com/dgidb/dgidb-v5/files/13651005/dec-2023-drugs.csv)
[dec-2023-genes.csv](https://github.com/dgidb/dgidb-v5/files/13651006/dec-2023-genes.csv)
[dec-2023-interactions.csv](https://github.com/dgidb/dgidb-v5/files/13651007/dec-2023-interactions.csv)

**Comment by mcannon068nw** [comment]
broken downloads data (TSVs, SQL) fixed by #462 and #463
