### ISSUE TITLE
TSV Version Numbers and Date

### ISSUE THREAD

**Issue by ecwood** [dgidb/dgidb-v5#513]
Hi! I work on RTX-KG2, which uses DGIdb's `interactions.tsv`. We try to encode the version and date of each of our sources in the knowledge graph. However, this is difficult with DGIdb if we want to use the latest version. Since the link for the latest version is https://www.dgidb.org/data/latest/interactions.tsv and the version number and date are not encoded in the TSV, we have to either use older versions (which include the date in the URL) or manually check the update date of the latest release before each build. It would be very helpful if DGIdb could include something like:
```
# Update Date: 2024-Jun
# Version Number: 5.0.7
```
at the top of `interactions.tsv`.

**Comment by mcannon068nw** [comment]
Thank you for the suggestion! We agree that this would be a very useful piece of information to include with our TSV releases. Going forward, we will include the version number and date within the file itself
