### ISSUE TITLE
Report Interaction Score components

### ISSUE THREAD

**Issue by paulflang** [dgidb/dgidb-v5#515]
IIUC `Interaction Score = evidence score * relative drug specificity * relative gene specificity`. Unfortunately, I can only find the Interaction Score, but not it's components in the Downloads section. Would it be possible to report the Interaction Score along with its three components? This would help us for filtering interactions.

**Comment by mcannon068nw** [comment]
Thank you! We agree these could be useful and informative data for how the interaction scores are calculated. We are looking into potentially including the calculated components alongside the interaction score in future data downloads.

**Comment by jsstevenson** [comment]
closed in #523

**Comment by paulflang** [comment]
Fantastic. Thank you!

**Comment by mcannon068nw** [comment]
hello @paulflang! I just wanted to reach out and let you know that these reported components are still coming. We ran into an unexpected data import issue while preparing the latest update. When this is resolved, new TSVs with these components reported will be released alongside the data update.

**Comment by paulflang** [comment]
Sounds good. Thank you very much for keeping me in the loop.
