### ISSUE TITLE
Capture some graphql query parameters for analytics

### ISSUE THREAD

**Issue by mcannon068nw** [dgidb/dgidb-v5#516]
Basic pageviews have already been implemented via https://github.com/dgidb/dgidb-v5/pull/466 but detailed analytics for graphql queries are not currently captured. While how much of the parameter set we should capture is undecided, we should at least capture gene and drug query terms to support grant development.

A method for how we might accomplish this has been generously provided by @acoffman : https://gist.github.com/acoffman/f40c92d8995d6598d479c23d125ff754

**Comment by mcannon068nw** [comment]
To add to this, we should see if perhaps we could find a way to capture ambiguous gene term selections. The idea being if a user uses the ambiguous genes tab, which gene do they select as their intended choice.

This would probably be helpful data for Anastasia to help untangle alias collisions

**Comment by mcannon068nw** [comment]
Per meeting, this will be addressed when we have available developer time

**Comment by jsstevenson** [comment]
> To add to this, we should see if perhaps we could find a way to capture ambiguous gene term selections. The idea being if a user uses the ambiguous genes tab, which gene do they select as their intended choice.

What we definitely *can* see is how often searches yield ambiguous matches, fwiw. I don't think it'd be too easy to see if they've tabbed over to the ambiguous tab unless we make the link from that tab slightly different so the server knows to log the request appropriately.

**Comment by jsstevenson** [comment]
Stuff to grab

* Query args -- particularly drug and gene terms
* Query type
* Approval rating stuff?

**Comment by jsstevenson** [comment]
I think we're calling this closed for now in https://github.com/dgidb/dgidb-v5/pull/526
