### ISSUE TITLE
JAX-CKB importer: Fix API breaks

### ISSUE THREAD

**Issue by jsstevenson** [dgidb/dgidb-v5#54]

**Comment by mcannon068nw** [comment]
deal with JAX for latest data set?

**Comment by mcannon068nw** [comment]
Content that was accessible for previous versions is now behind a $500 annual paywall branded as CKB BOOST (https://ckbhome.jax.org/register/signup). Additionally, this paywall also does not include the right to redistribute (https://ckbhome.jax.org/legal/eula)

**Comment by jsstevenson** [comment]
closed in #174
