### ISSUE TITLE
Directionality returns as "0" for both inhibiting and activating

### ISSUE THREAD

**Issue by cjosu** [dgidb/dgidb-v5#97]
Directly querying the db in rails console returns directionality `"activator"`, `"inhibitory"`,  or `"nil"`. The corresponding enum values expected from graphql are `0` for activator, `1` for inhibitory,  and `null` for nil. 

While 0 is returned for activator types (and null for nil types), graphql seems to also return 0 for inhibitory types.

**Comment by jsstevenson** [comment]
Double-check GraphQL enum representation -- maybe need additional mapping

**Comment by jsstevenson** [comment]
Closed in #110
